# Generated by Django 5.2.1 on 2025-05-21 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Xodimlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lavozim', models.CharField(max_length=100)),
                ('ishga_qabul_sana', models.DateTimeField(auto_now_add=True)),
                ('telefon_raqam', models.CharField(max_length=17)),
                ('manzil', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('user_role', models.CharField(choices=[('admin', 'Admin'), ('kadr', 'Kadr'), ('boshliq', 'Boshliq'), ('xodim', 'Xodim')], default='xodim', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Damvomat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kerish_vaqti', models.DateTimeField()),
                ('chiqish_vaqti', models.DateTimeField()),
                ('eslatmalar', models.CharField(blank=True, max_length=100, null=True)),
                ('status_r', models.CharField(choices=[('kelgan', 'Kelgan'), ('kelmagan', 'Kelmagan'), ('tatil', 'Tatil'), ('kechikkan', 'Kechikkan')], default='kelgan', max_length=20)),
                ('xodim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='davomat', to='davomat.xodimlar')),
            ],
            options={
                'verbose_name': 'Davomat',
                'verbose_name_plural': 'Davomatlar',
            },
        ),
    ]
