# Generated by Django 5.2.1 on 2025-05-22 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('davomat', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Damvomat',
            new_name='Davomat',
        ),
    ]
